FROM kalilinux/kali-rolling
RUN apt-get update && apt-get install -y python3 python3-pip tcpdump iproute2 iptables dos2unix
RUN pip3 install scapy --break-system-packages
COPY vuln_fw1.py /fw.py
COPY entrypoint.sh /entrypoint.sh
RUN dos2unix /entrypoint.sh && chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]
