name: openplc

services:
  plc:
    build: .
    container_name: openplc_controller
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    working_dir: /workdir/OpenPLC_v3/webserver
    command: python3 webserver.py
